In [4]:
print("Hello EuroPython!")


Hello EuroPython!


In [5]:
import numpy as np  
a = np.array([1, 2, 3, 4])
print(a)
A = np.array([1, 2, 3, 4])
A_t = A[:, np.newaxis]
print(A_t)
print(A_t.shape)
A = np.array([[1, 2, 3, 4]])
print(A)
print(A.T)


[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [6]:
1 / 100

0.01